/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'brand-purple': 'var(--brand-purple)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'surface-primary': 'var(--surface-primary)',
        'surface-secondary': 'var(--surface-secondary)',
        'surface-tertiary': 'var(--surface-tertiary)',
        'surface-active': 'var(--surface-active)',
        'surface-hover': 'var(--surface-hover)',
        'surface-submit': 'var(--surface-submit)',
        'surface-submit-hover': 'var(--surface-submit-hover)',
        'surface-destructive': 'var(--surface-destructive)',
        'surface-destructive-hover': 'var(--surface-destructive-hover)',
        'border-light': 'var(--border-light)',
        'border-medium': 'var(--border-medium)',
        'border-heavy': 'var(--border-heavy)',
        'sidebar-bg': 'var(--sidebar-bg)',
        'sidebar-fg': 'var(--sidebar-fg)',
        'sidebar-fg-muted': 'var(--sidebar-fg-muted)',
        'sidebar-fg-faint': 'var(--sidebar-fg-faint)',
        'sidebar-item-hover-bg': 'var(--sidebar-item-hover-bg)',
        'sidebar-item-hover-fg': 'var(--sidebar-item-hover-fg)',
        'sidebar-item-active-bg': 'var(--sidebar-item-active-bg)',
        'sidebar-item-active-fg': 'var(--sidebar-item-active-fg)',
        'sidebar-border': 'var(--sidebar-border)',
      },
      fontFamily: {
        sans: ['DM Sans', 'Inter', 'sans-serif'],
        mono: ['Roboto Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
